# Generated by Django 5.2.7 on 2025-11-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default='#3498db', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cook', 'Cocina'), ('waiter', 'Mesero'), ('cashier', 'Caja'), ('admin', 'Administrador')], default='waiter', max_length=20),
        ),
    ]
