# Generated by Django 5.2.6 on 2025-09-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PLATILLOS', 'Platillos'), ('BEBIDAS', 'Bebidas'), ('EXTRAS', 'Extras')], max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
