# Generated by Django 5.2.6 on 2025-09-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('FREE', 'Libre'), ('OCCUPIED', 'Ocupada'), ('RESERVED', 'Reservada')], default='FREE', max_length=10)),
            ],
        ),
    ]
