# Generated by Django 5.2.7 on 2025-11-12 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('mesero', '0005_table_assigned_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='mesero.table'),
        ),
    ]
