# Generated by Django 5.2.7 on 2025-10-03 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa_id', models.CharField(max_length=50, unique=True)),
                ('mesa', models.CharField(blank=True, help_text='Nombre/numero legible de la mesa', max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaiterOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('pedido', models.TextField(help_text='Detalle (items) del pedido')),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('nota', models.TextField(blank=True, null=True)),
                ('preparacion_enlazada', models.CharField(blank=True, help_text='opcional: id de orden en cocina', max_length=100, null=True)),
                ('estado', models.CharField(default='pendiente', help_text='pendiente, servido, pagado', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='mesero.table')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
