# Generated by you: create default mesas 1..5
from django.db import migrations

def create_default_tables(apps, schema_editor):
    Table = apps.get_model('mesero', 'Table')
    # crear mesas 1..5
    for i in range(1, 6):
        mesa_id = str(i)
        mesa_name = f"Mesa {i}"
        Table.objects.get_or_create(
            mesa_id=mesa_id,
            defaults={
                'mesa': mesa_name,
                # 'ubicacion': 'Sala principal',  # descomenta si tu modelo tiene 'ubicacion' y quieres rellenarla
            }
        )

def reverse_func(apps, schema_editor):
    Table = apps.get_model('mesero', 'Table')
    for i in range(1, 6):
        mesa_id = str(i)
        Table.objects.filter(mesa_id=mesa_id).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0001_initial'),  # ajusta si tu initial tiene otro nombre
    ]

    operations = [
        migrations.RunPython(create_default_tables, reverse_func),
    ]
