# Generated by Django 5.2.7 on 2025-11-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0002_create_default_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(default=4, help_text='Capacidad de personas'),
        ),
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.CharField(blank=True, help_text='Número de mesa visible', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Ocupada'), ('reserved', 'Reservada')], default='available', help_text='Estado de la mesa', max_length=20),
        ),
        migrations.AlterField(
            model_name='table',
            name='mesa',
            field=models.CharField(blank=True, help_text='Nombre/numero legible de la mesa - LEGACY', max_length=50, null=True),
        ),
    ]
