# Generated by Django 5.2.7 on 2025-11-11 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0003_table_capacity_table_number_table_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterorder',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mesero.table'),
        ),
    ]
