# Generated by Django 5.2.7 on 2025-11-12 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0004_alter_waiterorder_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='assigned_waiter',
            field=models.ForeignKey(blank=True, help_text='Mesero asignado a esta mesa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tables', to=settings.AUTH_USER_MODEL),
        ),
    ]
