# Generated by Django 5.2.7 on 2025-11-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesero', '0006_waiterorder_en_cocina_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterorder',
            name='estado',
            field=models.CharField(default='pendiente', help_text='pendiente, en_preparacion, listo, servido, facturado, pagado', max_length=50),
        ),
    ]
