# Generated by Django 5.2.7 on 2025-10-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.CharField(max_length=100, unique=True)),
                ('orden', models.TextField(help_text='Detalle de la orden (ingredientes, notas)')),
                ('plato', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_preparacion', 'En preparación'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='pendiente', help_text='Estado del pedido', max_length=50)),
                ('preparacion', models.TextField(blank=True, help_text='Detalles de preparación', null=True)),
                ('tiempo_estimado', models.IntegerField(default=0, help_text='Tiempo estimado en minutos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
